### ISSUE TITLE
API service crashes via URL manipulation

### ISSUE THREAD

**Issue by arturonuman** [OpenStackweb/userstory.openstack.org#5]
Steps to reproduce it:
- Navigate to http://localhost:9000/projectDetail/invalidID

Expected Behaviour:
- Let the user know, with an appropriate error message, the errors of the invalid ID.

Actual Behaviour:
- projectDetail page does not load correctly.
- Console error message is "Failed to load resource: net::ERR_EMPTY_RESPONSE"
- API service crashes.

![image](https://cloud.githubusercontent.com/assets/992561/21869770/c4af24ba-d81e-11e6-8610-d60520dc04e4.png)

![image](https://cloud.githubusercontent.com/assets/992561/21869742/a40fda4c-d81e-11e6-9012-bf5a5b40af92.png)

**Comment by viridianaJazel** [comment]
PR: https://github.com/OpenStackweb/userstory.openstack.org/pull/10
