### ISSUE TITLE
XSS via User Story JSON file.

### ISSUE THREAD

**Issue by arturonuman** [OpenStackweb/userstory.openstack.org#6]
Steps to reproduce it:
- Making use of an existing User Story JSON file, modify the 'description' property to include the string "<script>alert('XSS')</script>". e.g. "Capacity Management <script>alert('XSS')</script>"
- Reload the dashboard's home page.

Expected Behaviour:
- Data validation and encoding should be implemented in order to prevent XSS.

Actual Behaviour:
- Data validation and encoding is not being implemented and lets XSS to be executed.

![image](https://cloud.githubusercontent.com/assets/992561/21870032/04f32872-d820-11e6-8b3e-1ad14895bb39.png)

**Comment by teresita-guerrero** [comment]
- First approach sent for revision. 
- Validation is being done in the server side.
- It validate just the project list view
